routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BackendController@index')->name('home');
Route::post('/mediaTmp', 'BackendController@mediaTmp')->name('mediaTmp');

Route::resource('tags', 'TagController');

Route::resource('categories', 'CategoryController');

Route::resource('crews', 'CrewController');

Route::resource('movies', 'MovieController');
Route::match(['get', 'post'], 'movies/{movie}/crew', 'MovieController@crew')->name('movies.crew');
Route::match(['get', 'post'], 'movies/{movie}/moviefiles', 'MovieController@moviefiles')->name('movies.moviefiles');

Route::resource('movieFiles', 'MovieFileController');

Route::resource('reviews', 'ReviewController');

Route::resource('pages', 'PageController');

Route::resource('subscribers', 'SubscriberController');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::match(['get', 'post'], 'settings', 'BackendController@settings')->name('settings');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'FrontController@index');
Route::get('/main-search', 'FrontController@mainSearch')->name('mainSearch');

Route::get('/movies', 'FrontController@movies')->name('movies');
Route::get('/movies/{slug}', 'FrontController@movies_single')->name('movies.single');
Route::post('/movies/review/{id}', 'FrontController@movies_review')->name('movies.review');
Route::get('/movies/faved/{movie}', 'FrontController@movies_faved')->name('movies.faved');
Route::get('/movies/later/{movie}', 'FrontController@movies_later')->name('movies.later');
Route::get('/movies/watched/{movie}', 'FrontController@movies_watched')->name('movies.watched');

Route::get('/celebrities', 'FrontController@celebrities')->name('celebrities');
Route::get('/celebrities/{slug}', 'FrontController@celebrities_single')->name('celebrities.single');

Route::group(['middleware' => ['web', 'auth']], function () {
    Route::match(['get', 'post'], '/profile', 'FrontController@profile')->name('profile');
    Route::get('/profile/movies/{what}', 'FrontController@user_movies')->name('user_movies');
});

// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider', 'facebook|google');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google');

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;

class BackendController extends AppBaseController
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.home');
    }

    public function mediaTmp(Request $request)
    {
        $request->validate([
            'file' => 'required|image'
        ]);

        $path = storage_path('tmp/uploads');

        if (!file_exists($path)) {
            mkdir($path, 0777, true);
        }

        $file = $request->file('file');

        $name = uniqid() . '_' . trim($file->getClientOriginalName());

        $file->move($path, $name);

        return response()->json([
            'name'          => $name,
            'original_name' => $file->getClientOriginalName(),
        ]);
    }

    public function settings(Request $request)
    {
        if ($request->isMethod('get')) {
            return view('backend.settings');
        }

        if ($request->isMethod('post')) {
            settings()->set($request->all());
            settings()->save();
            Flash::success(__('messages.saved', ['model' => __('site.settings')]));
            return redirect(route('backend.settings'));
        }
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CategoryDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Repositories\CategoryRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class CategoryController extends AppBaseController
{
    /** @var  CategoryRepository */
    private $categoryRepository;

    public function __construct(CategoryRepository $categoryRepo)
    {
        $this->categoryRepository = $categoryRepo;
    }

    /**
     * Display a listing of the Category.
     *
     * @param CategoryDataTable $categoryDataTable
     * @return Response
     */
    public function index(CategoryDataTable $categoryDataTable)
    {
        return $categoryDataTable->render('backend.categories.index');
    }

    /**
     * Show the form for creating a new Category.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.categories.create');
    }

    /**
     * Store a newly created Category in storage.
     *
     * @param CreateCategoryRequest $request
     *
     * @return Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $input = $request->all();

        $category = $this->categoryRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/categories.singular')]));

        return redirect(route('backend.categories.index'));
    }

    /**
     * Display the specified Category.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('models/categories.singular').' '.__('messages.not_found'));

            return redirect(route('backend.categories.index'));
        }

        return view('backend.categories.show')->with('category', $category);
    }

    /**
     * Show the form for editing the specified Category.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('backend.categories.index'));
        }

        return view('backend.categories.edit')->with('category', $category);
    }

    /**
     * Update the specified Category in storage.
     *
     * @param  int              $id
     * @param UpdateCategoryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCategoryRequest $request)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('backend.categories.index'));
        }

        $category = $this->categoryRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/categories.singular')]));

        return redirect(route('backend.categories.index'));
    }

    /**
     * Remove the specified Category from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('backend.categories.index'));
        }

        if ($this->categoryRepository->delete($id)){
            Flash::success(__('messages.deleted', ['model' => __('models/categories.singular')]));
        } else {
            Flash::error(__('messages.deleted_error', ['model' => __('models/categories.singular')]));
        }


        return redirect(route('backend.categories.index'));
    }
}

app/Http/Controllers/Backend/CrewController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CrewDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCrewRequest;
use App\Http\Requests\UpdateCrewRequest;
use App\Repositories\CrewRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Models\Tag;
use Response;

class CrewController extends AppBaseController
{
    /** @var  CrewRepository */
    private $crewRepository;

    public function __construct(CrewRepository $crewRepo)
    {
        $this->crewRepository = $crewRepo;
    }

    /**
     * Display a listing of the Crew.
     *
     * @param CrewDataTable $crewDataTable
     * @return Response
     */
    public function index(CrewDataTable $crewDataTable)
    {
        return $crewDataTable->render('backend.crews.index');
    }

    /**
     * Show the form for creating a new Crew.
     *
     * @return Response
     */
    public function create()
    {
        $tags = Tag::all()->pluck('name', 'id');
        return view('backend.crews.create', compact('tags'));
    }

    /**
     * Store a newly created Crew in storage.
     *
     * @param CreateCrewRequest $request
     *
     * @return Response
     */
    public function store(CreateCrewRequest $request)
    {
        $input = $request->all();

        $crew = $this->crewRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/crews.singular')]));

        return redirect(route('backend.crews.index'));
    }

    /**
     * Display the specified Crew.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $crew = $this->crewRepository->find($id);

        if (empty($crew)) {
            Flash::error(__('models/crews.singular') . ' ' . __('messages.not_found'));

            return redirect(route('backend.crews.index'));
        }

        return view('backend.crews.show')->with('crew', $crew);
    }

    /**
     * Show the form for editing the specified Crew.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $crew = $this->crewRepository->find($id);

        if (empty($crew)) {
            Flash::error(__('messages.not_found', ['model' => __('models/crews.singular')]));

            return redirect(route('backend.crews.index'));
        }

        $tags = Tag::all()->pluck('name', 'id');
        return view('backend.crews.edit')->with('crew', $crew)->with('tags', $tags);
    }

    /**
     * Update the specified Crew in storage.
     *
     * @param  int              $id
     * @param UpdateCrewRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCrewRequest $request)
    {
        $crew = $this->crewRepository->find($id);

        if (empty($crew)) {
            Flash::error(__('messages.not_found', ['model' => __('models/crews.singular')]));

            return redirect(route('backend.crews.index'));
        }

        $input = $request->all();

        $crew = $this->crewRepository->update($input, $id);

        Flash::success(__('messages.updated', ['model' => __('models/crews.singular')]));

        return redirect(route('backend.crews.index'));
    }

    /**
     * Remove the specified Crew from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $crew = $this->crewRepository->find($id);

        if (empty($crew)) {
            Flash::error(__('messages.not_found', ['model' => __('models/crews.singular')]));

            return redirect(route('backend.crews.index'));
        }

        $this->crewRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/crews.singular')]));

        return redirect(route('backend.crews.index'));
    }
}

app/Http/Controllers/Backend/MovieController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\MovieDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateMovieRequest;
use App\Http\Requests\UpdateMovieRequest;
use App\Repositories\MovieRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Http\Requests\CrewMovieRequest;
use App\Http\Requests\FilesMovieRequest;
use App\Models\Crew;
use App\Models\Movie;
use App\Models\MovieFile;
use Response;

class MovieController extends AppBaseController
{
    /** @var  MovieRepository */
    private $movieRepository;

    public function __construct(MovieRepository $movieRepo)
    {
        $this->movieRepository = $movieRepo;
    }

    /**
     * Display a listing of the Movie.
     *
     * @param MovieDataTable $movieDataTable
     * @return Response
     */
    public function index(MovieDataTable $movieDataTable)
    {
        return $movieDataTable->render('backend.movies.index');
    }

    /**
     * Show the form for creating a new Movie.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.movies.create');
    }

    /**
     * Store a newly created Movie in storage.
     *
     * @param CreateMovieRequest $request
     *
     * @return Response
     */
    public function store(CreateMovieRequest $request)
    {
        $input = $request->all();

        $movie = $this->movieRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/movies.singular')]));

        return redirect(route('backend.movies.index'));
    }

    /**
     * Display the specified Movie.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $movie = $this->movieRepository->find($id);

        if (empty($movie)) {
            Flash::error(__('models/movies.singular') . ' ' . __('messages.not_found'));

            return redirect(route('backend.movies.index'));
        }

        return view('backend.movies.show')->with('movie', $movie);
    }

    /**
     * Show the form for editing the specified Movie.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $movie = $this->movieRepository->find($id);
        // dd($movie->gallery);
        if (empty($movie)) {
            Flash::error(__('messages.not_found', ['model' => __('models/movies.singular')]));

            return redirect(route('backend.movies.index'));
        }

        return view('backend.movies.edit')->with('movie', $movie);
    }

    /**
     * Update the specified Movie in storage.
     *
     * @param  int              $id
     * @param UpdateMovieRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMovieRequest $request)
    {
        $movie = $this->movieRepository->find($id);

        if (empty($movie)) {
            Flash::error(__('messages.not_found', ['model' => __('models/movies.singular')]));

            return redirect(route('backend.movies.index'));
        }

        $input = $request->all();

        $movie = $this->movieRepository->update($input, $id);

        Flash::success(__('messages.updated', ['model' => __('models/movies.singular')]));

        return redirect(route('backend.movies.index'));
    }

    /**
     * Remove the specified Movie from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $movie = $this->movieRepository->find($id);

        if (empty($movie)) {
            Flash::error(__('messages.not_found', ['model' => __('models/movies.singular')]));

            return redirect(route('backend.movies.index'));
        }

        $this->movieRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/movies.singular')]));

        return redirect(route('backend.movies.index'));
    }

    public function crew(CrewMovieRequest $request, Movie $movie)
    {
        if ($request->isMethod('get')) {
            $crews = Crew::select('id', 'name', 'position')->get();
            return view('backend.movies.crew', compact('crews', 'movie'));
        }

        if ($request->isMethod('post')) {
            $movie->crews()->sync($request->crews);
            Flash::success(__('messages.saved', ['model' => __('models/movies.singular')]));
            return redirect(route('backend.movies.index'));
        }
    }

    public function moviefiles(FilesMovieRequest $request, Movie $movie)
    {
        if ($request->isMethod('get')) {
            $moviefiles = MovieFile::select('id', 'name', 'se', 'ep', 'quality')->get();
            return view('backend.movies.moviefiles', compact('moviefiles', 'movie'));
        }

        if ($request->isMethod('post')) {
            $movie->movieFiles()->sync($request->movieFiles);
            Flash::success(__('messages.saved', ['model' => __('models/movies.singular')]));
            return redirect(route('backend.movies.index'));
        }
    }
}

resources/views/backend/layouts/app-lte.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>InfyOm Generator</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <!-- Select2 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">


    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    @yield('css')
</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <b>InfyOm</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="https://infyom.com/images/logo/blue_logo_150x150.jpg"
                                     class="user-image" alt="User Image"/>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{{ Auth::user()->name }}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="https://infyom.com/images/logo/blue_logo_150x150.jpg"
                                         class="img-circle" alt="User Image"/>
                                    <p>
                                        {{ Auth::user()->name }}
                                        <small>@lang('auth.app.member_since') {{ Auth::user()->created_at->format('M. Y') }}</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">@lang('auth.app.profile')</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{{ url('/logout') }}" class="btn btn-default btn-flat"
                                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            @lang('auth.sign_out')
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                              style="display: none;">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
    @include('layouts.sidebar')
    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2016 <a href="#">Company</a>.</strong> All rights reserved.
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    InfyOm Generator
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{{ url('/login') }}">Login</a></li>
                    <li><a href="{{ url('/register') }}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
@endif

<!-- jQuery 3.1.1 -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
<!-- AdminLTE App -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

@stack('scripts')
</body>
</html>

resources/views/backend/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/backend/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/backend/layouts/menu.blade.php
<li class="{{ Request::is('backend/users*') ? 'active' : '' }}">
    <a href="{{ route('backend.users.index') }}"><i class="fa fa-user"></i><span>@lang('models/users.plural')</span></a>
</li>

<li class="{{ Request::is('backend/tags*') ? 'active' : '' }}">
    <a href="{{ route('backend.tags.index') }}"><i class="fa fa-tags"></i><span>@lang('models/tags.plural')</span></a>
</li>

<li class="{{ Request::is('backend/categories*') ? 'active' : '' }}">
    <a href="{{ route('backend.categories.index') }}"><i class="fa fa-folder"></i><span>@lang('models/categories.plural')</span></a>
</li>

<li class="{{ Request::is('backend/crews*') ? 'active' : '' }}">
    <a href="{{ route('backend.crews.index') }}"><i class="fa fa-users"></i><span>@lang('models/crews.plural')</span></a>
</li>


<li class="{{ Request::is('backend/movies*') ? 'active' : '' }}">
    <a href="{{ route('backend.movies.index') }}"><i class="fa fa-video-camera"></i><span>@lang('models/movies.plural')</span></a>
</li>

<li class="{{ Request::is('backend/movieFiles*') ? 'active' : '' }}">
    <a href="{{ route('backend.movieFiles.index') }}"><i class="fa fa-file-movie-o"></i><span>@lang('models/movie_files.plural')</span></a>
</li>

<li class="{{ Request::is('backend/reviews*') ? 'active' : '' }}">
    <a href="{{ route('backend.reviews.index') }}"><i class="fa fa-star-half-empty"></i><span>@lang('models/reviews.plural')</span></a>
</li>

<li class="{{ Request::is('backend/pages*') ? 'active' : '' }}">
    <a href="{{ route('backend.pages.index') }}"><i class="fa fa-file"></i><span>@lang('models/pages.plural')</span></a>
</li>

<li class="{{ Request::is('backend/subscribers*') ? 'active' : '' }}">
    <a href="{{ route('backend.subscribers.index') }}"><i class="fa fa-flash"></i><span>@lang('models/subscribers.plural')</span></a>
</li>

<li class="{{ Request::is('backend/roles*') ? 'active' : '' }}">
    <a href="{{ route('backend.roles.index') }}"><i class="fa fa-anchor"></i><span>@lang('models/roles.plural')</span></a>
</li>

<li class="{{ Request::is('backend/settings*') ? 'active' : '' }}">
    <a href="{{ route('backend.settings') }}"><i class="fa fa-cog"></i><span>@lang('site.settings')</span></a>
</li>

resources/views/backend/layouts/sidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User Profile-->
        <div class="user-profile">
            <div class="user-pro-body">
                {{-- <div><img src="{{ asset('backend-files') }}/assets/images/users/2.jpg" alt="user-img" class="img-circle"></div> --}}
                <div class="dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle u-dropdown link hide-menu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>
                    <div class="dropdown-menu animated flipInY">
                        <!-- text-->
                        <a href="{{ route('backend.users.edit', auth()->id()) }}" class="dropdown-item"><i class="ti-user"></i> My Profile</a>
                        <div class="dropdown-divider"></div>
                        <!-- text-->
                        <div class="dropdown-divider"></div>
                        <!-- text-->
                        <a href="{{ url('/logout') }}" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-power-off"></i> @lang('auth.sign_out')</a>
                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;"> @csrf </form>
                        <!-- text-->
                    </div>
                </div>
            </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                @include('backend.layouts.menu')
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>