routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BackendController@index')->name('home');
Route::post('/mediaTmp', 'BackendController@mediaTmp')->name('mediaTmp');

Route::resource('tags', 'TagController');

Route::resource('categories', 'CategoryController');

Route::resource('crews', 'CrewController');

Route::resource('movies', 'MovieController');
Route::match(['get', 'post'], 'movies/{movie}/crew', 'MovieController@crew')->name('movies.crew');
Route::match(['get', 'post'], 'movies/{movie}/moviefiles', 'MovieController@moviefiles')->name('movies.moviefiles');

Route::resource('movieFiles', 'MovieFileController');

Route::resource('reviews', 'ReviewController');

Route::resource('pages', 'PageController');

Route::resource('subscribers', 'SubscriberController');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::match(['get', 'post'], 'settings', 'BackendController@settings')->name('settings');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'FrontController@index');
Route::get('/main-search', 'FrontController@mainSearch')->name('mainSearch');

Route::get('/movies', 'FrontController@movies')->name('movies');
Route::get('/movies/{slug}', 'FrontController@movies_single')->name('movies.single');
Route::post('/movies/review/{id}', 'FrontController@movies_review')->name('movies.review');
Route::get('/movies/faved/{movie}', 'FrontController@movies_faved')->name('movies.faved');
Route::get('/movies/later/{movie}', 'FrontController@movies_later')->name('movies.later');
Route::get('/movies/watched/{movie}', 'FrontController@movies_watched')->name('movies.watched');

Route::get('/celebrities', 'FrontController@celebrities')->name('celebrities');
Route::get('/celebrities/{slug}', 'FrontController@celebrities_single')->name('celebrities.single');

Route::group(['middleware' => ['web', 'auth']], function () {
    Route::match(['get', 'post'], '/profile', 'FrontController@profile')->name('profile');
    Route::get('/profile/movies/{what}', 'FrontController@user_movies')->name('user_movies');
});

// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider', 'facebook|google');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google');

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;

class BackendController extends AppBaseController
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.home');
    }

    public function mediaTmp(Request $request)
    {
        $request->validate([
            'file' => 'required|image'
        ]);

        $path = storage_path('tmp/uploads');

        if (!file_exists($path)) {
            mkdir($path, 0777, true);
        }

        $file = $request->file('file');

        $name = uniqid() . '_' . trim($file->getClientOriginalName());

        $file->move($path, $name);

        return response()->json([
            'name'          => $name,
            'original_name' => $file->getClientOriginalName(),
        ]);
    }

    public function settings(Request $request)
    {
        if ($request->isMethod('get')) {
            return view('backend.settings');
        }

        if ($request->isMethod('post')) {
            settings()->set($request->all());
            settings()->save();
            Flash::success(__('messages.saved', ['model' => __('site.settings')]));
            return redirect(route('backend.settings'));
        }
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CategoryDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Repositories\CategoryRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class CategoryController extends AppBaseController
{
    /** @var  CategoryRepository */
    private $categoryRepository;

    public function __construct(CategoryRepository $categoryRepo)
    {
        $this->categoryRepository = $categoryRepo;
    }

    /**
     * Display a listing of the Category.
     *
     * @param CategoryDataTable $categoryDataTable
     * @return Response
     */
    public function index(CategoryDataTable $categoryDataTable)
    {
        return $categoryDataTable->render('backend.categories.index');
    }

    /**
     * Show the form for creating a new Category.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.categories.create');
    }

    /**
     * Store a newly created Category in storage.
     *
     * @param CreateCategoryRequest $request
     *
     * @return Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $input = $request->all();

        $category = $this->categoryRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/categories.singular')]));

        return redirect(route('backend.categories.index'));
    }

    /**
     * Display the specified Category.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('models/categories.singular').' '.__('messages.not_found'));

            return redirect(route('backend.categories.index'));
        }

        return view('backend.categories.show')->with('category', $category);
    }

    /**
     * Show the form for editing the specified Category.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('backend.categories.index'));
        }

        return view('backend.categories.edit')->with('category', $category);
    }

    /**
     * Update the specified Category in storage.
     *
     * @param  int              $id
     * @param UpdateCategoryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCategoryRequest $request)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('backend.categories.index'));
        }

        $category = $this->categoryRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/categories.singular')]));

        return redirect(route('backend.categories.index'));
    }

    /**
     * Remove the specified Category from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('backend.categories.index'));
        }

        if ($this->categoryRepository->delete($id)){
            Flash::success(__('messages.deleted', ['model' => __('models/categories.singular')]));
        } else {
            Flash::error(__('messages.deleted_error', ['model' => __('models/categories.singular')]));
        }


        return redirect(route('backend.categories.index'));
    }
}

app/Http/Controllers/Backend/CrewController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CrewDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCrewRequest;
use App\Http\Requests\UpdateCrewRequest;
use App\Repositories\CrewRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Models\Tag;
use Response;

class CrewController extends AppBaseController
{
    /** @var  CrewRepository */
    private $crewRepository;

    public function __construct(CrewRepository $crewRepo)
    {
        $this->crewRepository = $crewRepo;
    }

    /**
     * Display a listing of the Crew.
     *
     * @param CrewDataTable $crewDataTable
     * @return Response
     */
    public function index(CrewDataTable $crewDataTable)
    {
        return $crewDataTable->render('backend.crews.index');
    }

    /**
     * Show the form for creating a new Crew.
     *
     * @return Response
     */
    public function create()
    {
        $tags = Tag::all()->pluck('name', 'id');
        return view('backend.crews.create', compact('tags'));
    }

    /**
     * Store a newly created Crew in storage.
     *
     * @param CreateCrewRequest $request
     *
     * @return Response
     */
    public function store(CreateCrewRequest $request)
    {
        $input = $request->all();

        $crew = $this->crewRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/crews.singular')]));

        return redirect(route('backend.crews.index'));
    }

    /**
     * Display the specified Crew.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $crew = $this->crewRepository->find($id);

        if (empty($crew)) {
            Flash::error(__('models/crews.singular') . ' ' . __('messages.not_found'));

            return redirect(route('backend.crews.index'));
        }

        return view('backend.crews.show')->with('crew', $crew);
    }

    /**
     * Show the form for editing the specified Crew.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $crew = $this->crewRepository->find($id);

        if (empty($crew)) {
            Flash::error(__('messages.not_found', ['model' => __('models/crews.singular')]));

            return redirect(route('backend.crews.index'));
        }

        $tags = Tag::all()->pluck('name', 'id');
        return view('backend.crews.edit')->with('crew', $crew)->with('tags', $tags);
    }

    /**
     * Update the specified Crew in storage.
     *
     * @param  int              $id
     * @param UpdateCrewRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCrewRequest $request)
    {
        $crew = $this->crewRepository->find($id);

        if (empty($crew)) {
            Flash::error(__('messages.not_found', ['model' => __('models/crews.singular')]));

            return redirect(route('backend.crews.index'));
        }

        $input = $request->all();

        $crew = $this->crewRepository->update($input, $id);

        Flash::success(__('messages.updated', ['model' => __('models/crews.singular')]));

        return redirect(route('backend.crews.index'));
    }

    /**
     * Remove the specified Crew from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $crew = $this->crewRepository->find($id);

        if (empty($crew)) {
            Flash::error(__('messages.not_found', ['model' => __('models/crews.singular')]));

            return redirect(route('backend.crews.index'));
        }

        $this->crewRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/crews.singular')]));

        return redirect(route('backend.crews.index'));
    }
}

app/Http/Controllers/Backend/MovieController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\MovieDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateMovieRequest;
use App\Http\Requests\UpdateMovieRequest;
use App\Repositories\MovieRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Http\Requests\CrewMovieRequest;
use App\Http\Requests\FilesMovieRequest;
use App\Models\Crew;
use App\Models\Movie;
use App\Models\MovieFile;
use Response;

class MovieController extends AppBaseController
{
    /** @var  MovieRepository */
    private $movieRepository;

    public function __construct(MovieRepository $movieRepo)
    {
        $this->movieRepository = $movieRepo;
    }

    /**
     * Display a listing of the Movie.
     *
     * @param MovieDataTable $movieDataTable
     * @return Response
     */
    public function index(MovieDataTable $movieDataTable)
    {
        return $movieDataTable->render('backend.movies.index');
    }

    /**
     * Show the form for creating a new Movie.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.movies.create');
    }

    /**
     * Store a newly created Movie in storage.
     *
     * @param CreateMovieRequest $request
     *
     * @return Response
     */
    public function store(CreateMovieRequest $request)
    {
        $input = $request->all();

        $movie = $this->movieRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/movies.singular')]));

        return redirect(route('backend.movies.index'));
    }

    /**
     * Display the specified Movie.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $movie = $this->movieRepository->find($id);

        if (empty($movie)) {
            Flash::error(__('models/movies.singular') . ' ' . __('messages.not_found'));

            return redirect(route('backend.movies.index'));
        }

        return view('backend.movies.show')->with('movie', $movie);
    }

    /**
     * Show the form for editing the specified Movie.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $movie = $this->movieRepository->find($id);
        // dd($movie->gallery);
        if (empty($movie)) {
            Flash::error(__('messages.not_found', ['model' => __('models/movies.singular')]));

            return redirect(route('backend.movies.index'));
        }

        return view('backend.movies.edit')->with('movie', $movie);
    }

    /**
     * Update the specified Movie in storage.
     *
     * @param  int              $id
     * @param UpdateMovieRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMovieRequest $request)
    {
        $movie = $this->movieRepository->find($id);

        if (empty($movie)) {
            Flash::error(__('messages.not_found', ['model' => __('models/movies.singular')]));

            return redirect(route('backend.movies.index'));
        }

        $input = $request->all();

        $movie = $this->movieRepository->update($input, $id);

        Flash::success(__('messages.updated', ['model' => __('models/movies.singular')]));

        return redirect(route('backend.movies.index'));
    }

    /**
     * Remove the specified Movie from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $movie = $this->movieRepository->find($id);

        if (empty($movie)) {
            Flash::error(__('messages.not_found', ['model' => __('models/movies.singular')]));

            return redirect(route('backend.movies.index'));
        }

        $this->movieRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/movies.singular')]));

        return redirect(route('backend.movies.index'));
    }

    public function crew(CrewMovieRequest $request, Movie $movie)
    {
        if ($request->isMethod('get')) {
            $crews = Crew::select('id', 'name', 'position')->get();
            return view('backend.movies.crew', compact('crews', 'movie'));
        }

        if ($request->isMethod('post')) {
            $movie->crews()->sync($request->crews);
            Flash::success(__('messages.saved', ['model' => __('models/movies.singular')]));
            return redirect(route('backend.movies.index'));
        }
    }

    public function moviefiles(FilesMovieRequest $request, Movie $movie)
    {
        if ($request->isMethod('get')) {
            $moviefiles = MovieFile::select('id', 'name', 'se', 'ep', 'quality')->get();
            return view('backend.movies.moviefiles', compact('moviefiles', 'movie'));
        }

        if ($request->isMethod('post')) {
            $movie->movieFiles()->sync($request->movieFiles);
            Flash::success(__('messages.saved', ['model' => __('models/movies.singular')]));
            return redirect(route('backend.movies.index'));
        }
    }
}

resources/views/backend/subscribers/create.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/subscribers.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.subscribers.index') }}">@lang('models/subscribers.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.add_new')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    @include('adminlte-templates::common.errors')

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!! Form::open(['route' => 'backend.subscribers.store']) !!}

                        @include('backend.subscribers.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\CreateSubscriberRequest', 'form')->ignore('.no-validate'); !!}
@endpush

resources/views/backend/subscribers/datatables_actions.blade.php
{!! Form::open(['route' => ['backend.subscribers.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('backend.subscribers.show', $id) }}" class='btn btn-outline-primary btn-sm'>
        <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('backend.subscribers.edit', $id) }}" class='btn btn-outline-info btn-sm'>
        <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-sm sa-btn-delete',
        'data-item' => $name,
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/backend/subscribers/edit.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/subscribers.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.subscribers.index') }}">@lang('models/subscribers.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.edit')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    @include('adminlte-templates::common.errors')

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!! Form::model($subscriber, ['route' => ['backend.subscribers.update', $subscriber->id], 'method' => 'patch']) !!}

                        @include('backend.subscribers.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\UpdateSubscriberRequest', 'form')->ignore('.no-validate'); !!}
@endpush

resources/views/backend/subscribers/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/subscribers.fields.name').':') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', __('models/subscribers.fields.email').':') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('backend.subscribers.index') }}" class="btn btn-default">@lang('crud.cancel')</a>
</div>

resources/views/backend/subscribers/index.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/subscribers.plural')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item active">@lang('models/subscribers.plural')</li>
                </ol>
                <a href="{{ route('backend.subscribers.create') }}" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @lang('crud.add_new')</a>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    @include('flash::message')

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    @include('backend.subscribers.table')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/subscribers/show.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/subscribers.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.subscribers.index') }}">@lang('models/subscribers.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.detail')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    @include('backend.subscribers.show_fields')
                    <a href="{{ route('backend.subscribers.index') }}" class="btn btn-default">
                        @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/subscribers/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', __('models/subscribers.fields.id').':') !!}
    <p>{{ $subscriber->id }}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', __('models/subscribers.fields.name').':') !!}
    <p>{{ $subscriber->name }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', __('models/subscribers.fields.email').':') !!}
    <p>{{ $subscriber->email }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', __('models/subscribers.fields.created_at').':') !!}
    <p>{{ $subscriber->created_at }}</p>
</div>

resources/views/backend/subscribers/table.blade.php
@section('css')
    @include('backend.layouts.datatables_css')
@endsection
<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('scripts')
    @include('backend.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush